# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Window(QtWidgets.QWidget):
    forecast_types = {
        'rain-3h': "о",
        'gust': "в",
        'wave': "вол"}
    dir_name = QtCore.QDir.currentPath()

    def __init__(self, ventu_parser, parent=None):
        QtWidgets.QWidget.__init__(self, parent)

        self.ventuParser = ventu_parser

        self.setWindowTitle("Нарезатель слайдов")
        self.resize(320, 275)
        self.setMaximumSize(QtCore.QSize(320, 275))

        self.checkBox_prep = QtWidgets.QCheckBox("Осадки")
        self.checkBox_prep.toggle()
        self.checkBox_prep.stateChanged.connect(self.add_or_del_prep)

        self.vbox = QtWidgets.QVBoxLayout()

        self.vbox.addWidget(self.checkBox_prep, 0, QtCore.Qt.AlignHCenter)

        self.checkBox_gust = QtWidgets.QCheckBox("Порывы ветра")
        self.checkBox_gust.setMaximumSize(QtCore.QSize(16777215, 130))
        self.checkBox_gust.toggle()
        self.checkBox_gust.stateChanged.connect(self.add_or_del_gust)

        self.vbox.addWidget(self.checkBox_gust, 0, QtCore.Qt.AlignHCenter)

        self.btn_choose_dir = QtWidgets.QPushButton("Выбрать папку")
        self.btn_choose_dir.clicked.connect(self.choose_dir)

        self.vbox.addWidget(self.btn_choose_dir)

        self.btnStart = QtWidgets.QPushButton("Запуск")
        self.btnStart.clicked.connect(self.on_start)
        self.btnGismeteo = QtWidgets.QPushButton("Загрузить с Gismeteo")
        self.btnGismeteo.clicked.connect(self.get_gismeteo)

        self.vbox.addWidget(self.btnStart)
        self.vbox.addWidget(self.btnGismeteo)
        # self.hbox.addLayout(self.vbox)

        self.label = QtWidgets.QLabel(Window.dir_name)
        self.vbox.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)

        self.setLayout(self.vbox)

    def choose_dir(self):
        Window.dir_name = QtWidgets.QFileDialog.getExistingDirectory(directory=Window.dir_name)
        self.label.setText(Window.dir_name)
        self.ventuParser.set_dir(Window.dir_name)

    def add_or_del_prep(self, state):
        if state == QtCore.Qt.Checked:
            Window.forecast_types['rain-3h'] = 'Осадки'
        else:
            if 'rain-3h' in Window.forecast_types.keys():
                Window.forecast_types.pop('rain-3h')
        self.ventuParser.fTypes = self.forecast_types

    def add_or_del_gust(self, state):
        if state == QtCore.Qt.Checked:
            Window.forecast_types['gust'] = 'Порывы'
        else:
            if 'gust' in Window.forecast_types.keys():
                Window.forecast_types.pop('gust')
        self.ventuParser.fTypes = self.forecast_types


    def on_start(self):
        self.ventuParser.launch_driver()

    def get_gismeteo(self):
        self.ventuParser.get_gismeteo()